version: '1.0'

services:
  neo4j:
    image: neo4j:latest
    container_name: practica2_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: neo4j/password
    restart: always

networks:
  practica2_network:
    driver: bridge